### ISSUE TITLE
Hi, my friend

### ISSUE THREAD

**Issue by leninalbertolp** [ayinloya/materialized-css-snippets#11]
I write, because I have a similar to yours, repository with snippets for Materializecss, I wonder if you have interest in continuing your plugin.

Try to upload my plugin to control package, but was denied because that same make as yours.
I'd like to know if we can work together in order to provide a good experience to the user

[Link to my repository](https://github.com/leninalbertolp/materializecss-snippets)

**Comment by ayinloya** [comment]
Hi @leninalbertolp , I'll continue to work on the plugin, I'm open to contributions. Let me know how best we can work together. If it's okay with you, you can create a pull request.

**Comment by ayinloya** [comment]
Any update?
