### ISSUE TITLE
can this be available for Atom.io editor by github?

### ISSUE THREAD

**Issue by RYG81** [ayinloya/materialized-css-snippets#12]
HI,
Can you please make this for Atom editor by Github too?
Rahul

**Comment by ayinloya** [comment]
If a similar package is not available, I'll try to make Atom Editor version.
Thanks for the request

**Comment by RYG81** [comment]
I did not find similar for Atom and that is why I requested for this.
Thanks for making it in advance.
Rahul

**Comment by RYG81** [comment]
any update?

**Comment by ayinloya** [comment]
I started a new project on it, looks like it will take awhile though

**Comment by RYG81** [comment]
Thank You very much.

**Comment by ayinloya** [comment]
@RYG81 This is the link to the beta version of the package for atom [https://atom.io/packages/materialize-css](https://atom.io/packages/materialize-css)

**Comment by ayinloya** [comment]
The First version has minimal snippets, I'll keep updating it. This issue will be closed for now. Thanks for the request @RYG81
