### ISSUE TITLE
m-lg-button snippet has a bug

### ISSUE THREAD

**Issue by animeshsinghweb** [ayinloya/materialized-css-snippets#13]
When I use `m-lg-button`, it gives this snippet output:

`<button type="button" class="waves-effect waves-light btn-large"><i class="material-icons right">{4:cloud</i>}</button>`

Over there I can't find `{4:cloud</i>}` relative. Maybe that {} and 4:cloud is a bug.

Anyways, let me know what's it purpose.
Thanks

**Comment by ayinloya** [comment]
Hi @animeshsinghweb, I'll check it up

**Comment by animeshsinghweb** [comment]
Sure, :)

**Comment by ayinloya** [comment]
This should be fixed with the new update
