### ISSUE TITLE
m-sticky-footer:css not working 

### ISSUE THREAD

**Issue by vaidhyanathan93** [ayinloya/materialized-css-snippets#3]
In windows sublime3 it is not expanding to correct output

**Comment by ayinloya** [comment]
Thank you for the notice. @theprinceanim  just made a fix, let me know whether it's solved or not.

**Comment by vaidhyanathan93** [comment]
No Yet to resolve .I hope it need to expand inside a style tag, but not expanding . Hope i am right 
![screenshot from 2015-05-01 10 10 02](https://cloud.githubusercontent.com/assets/3818495/7426744/707f171a-efea-11e4-9ca0-d2ce7521de0a.png)

**Comment by ayinloya** [comment]
try checking the m-sticky-footer:css again and let know if its fixed.

**Comment by ayinloya** [comment]
Ok thanks @vaidhyanathan93 now that all's well,  I'm closing this issue
