### ISSUE TITLE
Weird indention in snippets

### ISSUE THREAD

**Issue by mlazaric** [ayinloya/materialized-css-snippets#7]
You seem to have a lot of random indention in files and when you try to use the snippet, it's not indented properly. So if you'll allow it, I'd like to create a pull request to fix the indention in all snippets. 

Example: https://github.com/logomaster256/materialized-css-snippets/commit/fc8a1d9d65b5ce5e460e1d59f9ef7d720b5f8c74

Thank you for making such a helpful package and have a nice day!

**Comment by Dogfalo** [comment]
:+1:

**Comment by mlazaric** [comment]
Now that it's merged, you only need to create a release and we can close this issue.

**Comment by mlazaric** [comment]
Everything appear to be working so I'll close this issue.

Have a nice day!

**Comment by ayinloya** [comment]
:thumbsup: Great
